## If a reboot is needed to be generated by the script, this script must exit before the reboot, so shell out to reboot, then exit with 1
#Start-Process -FilePath "cmd.exe" -ArgumentList '/c "timeout /t 3 /nobreak && shutdown -r -f -t 0"' -WindowStyle Hidden
#exit 1



write-host "TRunning the Audit Mode script..."


#Download and execute the cleanup script
Invoke-restmethod https://raw.githubusercontent.com/WoodneyUK/OOBE/main/CleanUp.ps1 | out-file "c:\windows\setup\scripts\LLCleanup.ps1" -force -encoding ascii
& "c:\windows\setup\scripts\LLCleanup.ps1"







# Finalize the device and return to OOBE

rename-item -path c:\windows\panther\unattend\unattend.xml -newname unattend.old
rename-item -path c:\windows\panther\unattend\oobe.xml -newname unattend.xml
start-process -filepath "c:\windows\system32\sysprep\sysprep.exe" -argumentlist "/quiet /reboot /oobe /unattend:c:\windows\panther\unattend\unattend.xml" -wait

#with reboot
exit 1
